name: plata_sync
description: "Plata Sync - Personal Financial Management app."
publish_to: 'none'
version: 0.0.2+2

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: 3.38.7

dependencies:
  equatable: ^2.0.8
  file_saver: ^0.3.1
  file_selector: ^1.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  hugeicons: ^1.1.5
  intl: ^0.20.2
  math_expressions: ^3.1.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.4
  restart_app: ^1.3.2
  shared_preferences: ^2.5.4
  sqflite: ^2.4.1
  sqflite_common_ffi: ^2.4.0+2
  uuid: ^4.5.2
  vector_graphics: ^1.1.19
  watch_it: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/fonts/Noto_Sans/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon_light_inline.png"
    background_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/app_icon_light_inline.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon_light_inline.png"
  linux:
    generate: true
    image_path: "assets/icons/app_icon_light_inline.png"
  image_path: "assets/icons/app_icon_light_inline.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/app_icon_light_inline.png"
  remove_alpha_ios: true
