name: plata_sync
description: "Plata Sync - Personal Financial Management app."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.10.1
  flutter: 3.38.3

dependencies:
  flutter:
    sdk: flutter
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
