name: plata_sync
description: "Plata Sync - Personal Financial Management app."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.10.1
  flutter: 3.38.3

dependencies:
  equatable: ^2.0.7
  flex_color_scheme: ^8.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get_it: ^9.1.1
  go_router: ^17.0.0
  hugeicons: ^1.1.1
  intl: ^0.20.2
  package_info_plus: ^8.1.2
  path: ^1.9.1
  shared_preferences: ^2.3.5
  sqflite: ^2.4.1
  uuid: ^4.5.2
  watch_it: ^2.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
